/**
 * STEM Compass — Question Bank
 * Covers: mathematics, computer_science, mixed
 * Respondents: learner, parent, teacher
 * Profiles: child, teen, adult
 * Modes: express, standard, complete
 */

// ─────────────────────────────────────────────
// SECTION CONFIGURATION
// Keys per domain / profile / mode
// ─────────────────────────────────────────────

export const SECTION_CONFIG = {
  child: {
    express: ["common_goal", "common_blocage", "common_error", "math_mini_tasks"],
    standard: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "math_mini_tasks"],
    complete: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "math_mini_tasks", "parent_context", "teacher_observation"],
  },
  teen: {
    express: ["common_goal", "common_blocage", "common_error", "math_mini_tasks"],
    standard: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "math_mini_tasks"],
    complete: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "math_mini_tasks", "parent_context", "teacher_observation"],
  },
  adult: {
    express: ["common_goal", "common_blocage", "common_error"],
    standard: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile"],
    complete: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "math_mini_tasks", "teacher_observation"],
  },
};

// Computer science overrides (replace math sections with CS sections)
export const SECTION_CONFIG_CS = {
  child: {
    express: ["common_goal", "common_blocage", "common_error", "cs_mini_tasks"],
    standard: ["common_goal", "common_blocage", "common_error", "common_method", "cs_profile", "cs_mini_tasks"],
    complete: ["common_goal", "common_blocage", "common_error", "common_method", "cs_profile", "cs_mini_tasks", "parent_context", "teacher_observation"],
  },
  teen: {
    express: ["common_goal", "common_blocage", "common_error", "cs_mini_tasks"],
    standard: ["common_goal", "common_blocage", "common_error", "common_method", "cs_profile", "cs_mini_tasks"],
    complete: ["common_goal", "common_blocage", "common_error", "common_method", "cs_profile", "cs_mini_tasks", "parent_context", "teacher_observation"],
  },
  adult: {
    express: ["common_goal", "common_blocage", "common_error"],
    standard: ["common_goal", "common_blocage", "common_error", "common_method", "cs_profile"],
    complete: ["common_goal", "common_blocage", "common_error", "common_method", "cs_profile", "cs_mini_tasks", "teacher_observation"],
  },
};

export const SECTION_CONFIG_MIXED = {
  child: {
    express: ["common_goal", "common_blocage", "common_error", "math_mini_tasks"],
    standard: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "cs_profile", "math_mini_tasks"],
    complete: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "cs_profile", "math_mini_tasks", "cs_mini_tasks", "parent_context", "teacher_observation"],
  },
  teen: {
    express: ["common_goal", "common_blocage", "common_error", "math_mini_tasks"],
    standard: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "cs_profile", "math_mini_tasks"],
    complete: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "cs_profile", "math_mini_tasks", "cs_mini_tasks", "parent_context", "teacher_observation"],
  },
  adult: {
    express: ["common_goal", "common_blocage", "common_error"],
    standard: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "cs_profile"],
    complete: ["common_goal", "common_blocage", "common_error", "common_method", "math_profile", "cs_profile", "math_mini_tasks", "cs_mini_tasks", "teacher_observation"],
  },
};

/** Get sections for a given domain / profile / mode */
export function getSectionsForDomain(domain, profile, mode) {
  if (domain === "computer_science") return SECTION_CONFIG_CS[profile]?.[mode] || [];
  if (domain === "mixed") return SECTION_CONFIG_MIXED[profile]?.[mode] || [];
  return SECTION_CONFIG[profile]?.[mode] || [];
}

// ─────────────────────────────────────────────
// SECTION METADATA
// ─────────────────────────────────────────────

export const SECTION_META = {
  common_goal: {
    title: "Objectif réel",
    desc: "Comprendre ce que l'élève veut vraiment accomplir",
    respondent: "learner",
    estimated: 3,
    required: "required",
    domain: "all",
  },
  common_blocage: {
    title: "Blocage principal",
    desc: "Identifier où l'élève bloque le plus souvent",
    respondent: "learner",
    estimated: 3,
    required: "required",
    domain: "all",
  },
  common_error: {
    title: "Rapport à l'erreur",
    desc: "Comment l'élève réagit face à l'erreur",
    respondent: "learner",
    estimated: 2,
    required: "required",
    domain: "all",
  },
  common_method: {
    title: "Méthode de travail",
    desc: "Ce qui aide l'élève quand il ne comprend pas",
    respondent: "learner",
    estimated: 3,
    required: "recommended",
    domain: "all",
  },
  math_profile: {
    title: "Profil mathématiques",
    desc: "Calculs, formules, énoncés, rédaction",
    respondent: "learner",
    estimated: 5,
    required: "recommended",
    domain: "mathematics",
  },
  cs_profile: {
    title: "Profil informatique",
    desc: "Code, logique, debugging, lecture/écriture",
    respondent: "learner",
    estimated: 5,
    required: "recommended",
    domain: "computer_science",
  },
  math_mini_tasks: {
    title: "Mini-tâches maths",
    desc: "Quelques exercices courts pour situer les besoins",
    respondent: "learner",
    estimated: 5,
    required: "optional",
    domain: "mathematics",
  },
  cs_mini_tasks: {
    title: "Mini-tâches informatique",
    desc: "Quelques exercices courts pour situer les besoins",
    respondent: "learner",
    estimated: 5,
    required: "optional",
    domain: "computer_science",
  },
  parent_context: {
    title: "Contexte parent",
    desc: "Ce que le parent observe au quotidien",
    respondent: "parent",
    estimated: 5,
    required: "recommended",
    domain: "all",
  },
  teacher_observation: {
    title: "Observation professeur",
    desc: "Raisonnement, autonomie, erreurs, posture pédagogique",
    respondent: "teacher",
    estimated: 6,
    required: "recommended",
    domain: "all",
  },
};

// ─────────────────────────────────────────────
// QUESTIONS
// ─────────────────────────────────────────────

export const QUESTIONS = [

  // ── OBJECTIF RÉEL ──────────────────────────

  {
    id: "goal_01",
    section_key: "common_goal",
    domain: "mathematics",
    audience: "learner",
    profile: "child",
    mode: "all",
    question_text: "Qu'est-ce que tu aimerais réussir à faire plus facilement en maths ?",
    answer_type: "single_choice",
    options: [
      "Comprendre les consignes",
      "Faire les calculs sans paniquer",
      "Réussir les problèmes",
      "Expliquer ma réponse",
      "Apprendre mes formules",
      "Faire mes devoirs plus seul",
      "Avoir moins peur des exercices",
    ],
    required_status: "required",
    pedagogical_purpose: "Identifier l'objectif motivationnel et le niveau d'anxiété face aux maths",
    output_usage: ["teacher_brief", "first_lesson_plan", "method_recommendation"],
  },

  {
    id: "goal_02",
    section_key: "common_goal",
    domain: "computer_science",
    audience: "learner",
    profile: "child",
    mode: "all",
    question_text: "Qu'est-ce que tu aimerais réussir à faire en informatique ?",
    answer_type: "single_choice",
    options: [
      "Comprendre le code",
      "Écrire un petit programme",
      "Corriger mes erreurs",
      "Comprendre les consignes",
      "Savoir par où commencer",
      "Faire un projet",
      "Ne pas paniquer face aux messages d'erreur",
    ],
    required_status: "required",
    pedagogical_purpose: "Identifier l'objectif et le rapport à l'erreur en programmation",
    output_usage: ["teacher_brief", "first_lesson_plan", "method_recommendation"],
  },

  {
    id: "goal_03",
    section_key: "common_goal",
    domain: "mathematics",
    audience: "learner",
    profile: "teen",
    mode: "all",
    question_text: "Qu'est-ce que tu aimerais réussir à faire que tu ne fais pas encore facilement en maths ?",
    answer_type: "single_choice",
    options: [
      "Résoudre un problème seul",
      "Comprendre les énoncés",
      "Savoir quelle méthode utiliser",
      "Mieux rédiger mes réponses",
      "Moins paniquer en contrôle",
      "Comprendre les formules",
      "Rattraper mes bases",
      "Préparer un examen",
    ],
    required_status: "required",
    pedagogical_purpose: "Objectif scolaire ou personnel, niveau de confiance",
    output_usage: ["teacher_brief", "first_lesson_plan", "method_recommendation"],
  },

  {
    id: "goal_04",
    section_key: "common_goal",
    domain: "computer_science",
    audience: "learner",
    profile: "teen",
    mode: "all",
    question_text: "Qu'est-ce que tu aimerais réussir à faire en informatique ou en programmation ?",
    answer_type: "single_choice",
    options: [
      "Comprendre un exercice de code",
      "Écrire un programme sans être bloqué",
      "Comprendre les messages d'erreur",
      "Utiliser les boucles et fonctions",
      "Résoudre un problème étape par étape",
      "Faire un projet personnel",
      "Préparer un examen",
      "Mieux raisonner en algorithmique",
    ],
    required_status: "required",
    pedagogical_purpose: "Objectif scolaire ou personnel en programmation",
    output_usage: ["teacher_brief", "first_lesson_plan", "method_recommendation"],
  },

  {
    id: "goal_05",
    section_key: "common_goal",
    domain: "all",
    audience: "learner",
    profile: "adult",
    mode: "all",
    question_text: "Dans quel contexte avez-vous besoin de progresser ?",
    answer_type: "single_choice",
    options: [
      "Études",
      "Examen",
      "Reconversion professionnelle",
      "Projet personnel",
      "Travail",
      "Data / analyse",
      "Programmation",
      "Remise à niveau",
      "Concours",
      "Autre",
    ],
    required_status: "required",
    pedagogical_purpose: "Contexte et enjeu réel de l'apprentissage",
    output_usage: ["teacher_brief", "first_lesson_plan", "method_recommendation"],
  },

  {
    id: "goal_06",
    section_key: "common_goal",
    domain: "all",
    audience: "learner",
    profile: "teen",
    mode: "standard",
    question_text: "Quelle situation te donnerait vraiment l'impression d'avoir progressé ?",
    answer_type: "short_text",
    max_words: 180,
    required_status: "recommended",
    pedagogical_purpose: "Identifier l'indicateur de succès personnel de l'élève",
    output_usage: ["learner_summary", "plan_4_weeks"],
  },

  {
    id: "goal_07",
    section_key: "common_goal",
    domain: "all",
    audience: "learner",
    profile: "adult",
    mode: "standard",
    question_text: "Quelle réussite concrète vous ferait dire : 'je progresse vraiment' ?",
    answer_type: "short_text",
    max_words: 180,
    required_status: "recommended",
    pedagogical_purpose: "Indicateur de succès, motivation intrinsèque",
    output_usage: ["learner_summary", "plan_4_weeks"],
  },

  // ── BLOCAGE PRINCIPAL ──────────────────────

  {
    id: "block_01",
    section_key: "common_blocage",
    domain: "all",
    audience: "learner",
    profile: "all",
    mode: "all",
    question_text: "À quel moment tu bloques le plus souvent ?",
    child_text: "Quand est-ce que ça devient difficile pour toi ?",
    answer_type: "single_choice",
    options: [
      "Au moment de comprendre la consigne",
      "Au moment de commencer",
      "Pendant les calculs ou le code",
      "Quand il faut choisir une méthode",
      "Quand il y a une erreur",
      "Quand il faut expliquer ma réponse",
      "Quand l'exercice change un peu",
      "Quand je dois travailler seul",
      "Je ne sais pas précisément",
    ],
    required_status: "required",
    pedagogical_purpose: "Identifier le moment critique de blocage dans le processus de résolution",
    output_usage: ["teacher_brief", "method_recommendation", "first_lesson_plan"],
    interpretation_rules: {
      "Au moment de comprendre la consigne": "Priorité : travail sur la lecture d'énoncé et la reformulation",
      "Au moment de commencer": "Priorité : méthode de démarrage, décomposition du problème",
      "Quand il faut choisir une méthode": "Priorité : reconnaissance de types d'exercices, catalogue de stratégies",
      "Quand il y a une erreur": "Priorité : tolérance à l'erreur, debugging, correction guidée",
      "Quand il faut expliquer ma réponse": "Priorité : verbalisation, rédaction mathématique",
      "Quand l'exercice change un peu": "Priorité : transfert et compréhension profonde",
    },
  },

  {
    id: "block_02",
    section_key: "common_blocage",
    domain: "all",
    audience: "learner",
    profile: "all",
    mode: "standard",
    question_text: "Qu'est-ce qui te donne le plus l'impression d'être perdu ?",
    child_text: "Quand tu te sens le plus perdu, c'est à cause de quoi ?",
    answer_type: "single_choice",
    options: [
      "Trop d'informations dans l'énoncé",
      "Je ne vois pas quelle formule ou méthode utiliser",
      "Je fais des erreurs de calcul ou de syntaxe",
      "Je comprends l'exemple mais pas l'exercice seul",
      "Je ne sais pas vérifier ma réponse",
      "Je vais trop lentement",
      "Je panique quand je me trompe",
      "Autre",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Préciser la nature du blocage cognitif dominant",
    output_usage: ["method_recommendation", "first_lesson_plan", "error_watchlist"],
  },

  // ── RAPPORT À L'ERREUR ─────────────────────

  {
    id: "err_01",
    section_key: "common_error",
    domain: "all",
    audience: "learner",
    profile: "all",
    mode: "all",
    question_text: "Quand tu fais une erreur, que fais-tu généralement ?",
    child_text: "Quand tu te trompes dans un exercice, qu'est-ce que tu fais ?",
    answer_type: "single_choice",
    options: [
      "J'essaie de comprendre d'où elle vient",
      "Je recommence depuis le début",
      "Je demande de l'aide",
      "Je change de méthode au hasard",
      "Je me bloque",
      "Je pense que je suis nul(le)",
      "Je passe à autre chose",
      "Je ne sais pas",
    ],
    required_status: "required",
    pedagogical_purpose: "Profil métacognitif face à l'erreur : analyse, panique, évitement, délégation",
    output_usage: ["teacher_brief", "correction_strategy", "confidence_support"],
    interpretation_rules: {
      "J'essaie de comprendre d'où elle vient": "Bon levier métacognitif — à valoriser",
      "Je recommence depuis le début": "Besoin de stratégie de correction ciblée",
      "Je change de méthode au hasard": "Besoin de méthode et de critères de choix",
      "Je me bloque": "Priorité : sécurité émotionnelle, droit à l'erreur",
      "Je pense que je suis nul(le)": "Priorité : confiance, reformulation de l'erreur comme apprentissage",
      "Je passe à autre chose": "Persévérance à travailler, capacité de récupération",
    },
  },

  {
    id: "err_02",
    section_key: "common_error",
    domain: "all",
    audience: "learner",
    profile: "teen",
    mode: "standard",
    question_text: "Quand tu te trompes dans un exercice difficile, tu ressens plutôt…",
    answer_type: "single_choice",
    options: [
      "De la frustration mais j'essaie de comprendre",
      "De la honte ou de la gêne",
      "Rien de particulier, c'est normal",
      "L'envie d'abandonner",
      "La curiosité de comprendre l'erreur",
      "Une grande démotivation",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Rapport émotionnel à l'erreur, risque de démotivation",
    output_usage: ["confidence_support", "teacher_brief"],
  },

  // ── MÉTHODE DE TRAVAIL ─────────────────────

  {
    id: "meth_01",
    section_key: "common_method",
    domain: "all",
    audience: "learner",
    profile: "all",
    mode: "standard",
    question_text: "Quand tu ne comprends pas un exercice, qu'est-ce qui t'aide le plus ?",
    child_text: "Quand tu ne comprends pas, qu'est-ce qui t'aide ?",
    answer_type: "single_choice",
    options: [
      "Voir un exemple similaire",
      "Refaire une étape lentement",
      "Qu'on m'explique la méthode",
      "Qu'on me pose des questions",
      "Dessiner ou faire un schéma",
      "Essayer plusieurs pistes",
      "Voir la correction",
      "Travailler avec quelqu'un",
      "Je ne sais pas",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Style d'apprentissage préféré et mode d'accès à la compréhension",
    output_usage: ["method_recommendation", "first_lesson_plan", "activity_personalization"],
  },

  {
    id: "meth_02",
    section_key: "common_method",
    domain: "all",
    audience: "learner",
    profile: "teen",
    mode: "standard",
    question_text: "Quand tu réussis un exercice, sais-tu expliquer pourquoi ta méthode marche ?",
    answer_type: "single_choice",
    options: [
      "Oui, souvent",
      "Parfois",
      "Rarement",
      "Non",
      "Je peux refaire mais pas expliquer",
      "Je ne sais pas",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Distinction apprentissage procédural vs compréhension conceptuelle",
    output_usage: ["teacher_brief", "method_recommendation", "reasoning_profile"],
    interpretation_rules: {
      "Je peux refaire mais pas expliquer": "Apprentissage procédural — compréhension fragile, priorité à la verbalisation",
      "Parfois": "Verbalisation à renforcer",
      "Oui, souvent": "Autonomie possible — aller vers la généralisation",
    },
  },

  {
    id: "meth_03",
    section_key: "common_method",
    domain: "all",
    audience: "learner",
    profile: "adult",
    mode: "standard",
    question_text: "Quelle approche vous aide le mieux à apprendre ?",
    answer_type: "single_choice",
    options: [
      "Comprendre la logique avant la technique",
      "Pratiquer directement et ajuster",
      "Voir un exemple complet d'abord",
      "Travailler étape par étape avec du guidage",
      "Travailler seul à mon rythme",
      "Alterner théorie et pratique",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Style d'apprentissage adulte, autonomie",
    output_usage: ["method_recommendation", "first_lesson_plan"],
  },

  // ── PROFIL MATHÉMATIQUES ───────────────────

  {
    id: "math_01",
    section_key: "math_profile",
    domain: "mathematics",
    audience: "learner",
    profile: "all",
    mode: "standard",
    question_text: "Qu'est-ce qui te pose le plus souvent problème en maths ?",
    answer_type: "multiple_choice",
    options: [
      "Les calculs",
      "Les fractions",
      "Les équations",
      "Les fonctions",
      "La géométrie",
      "Les probabilités / statistiques",
      "Les problèmes avec texte",
      "Les formules",
      "La rédaction de la réponse",
      "Comprendre le cours",
      "Je ne sais pas",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Identifier les domaines mathématiques problématiques",
    output_usage: ["teacher_brief", "error_watchlist", "first_lesson_plan"],
  },

  {
    id: "math_02",
    section_key: "math_profile",
    domain: "mathematics",
    audience: "learner",
    profile: "all",
    mode: "standard",
    question_text: "Quand tu vois un problème avec du texte, que fais-tu d'abord ?",
    answer_type: "single_choice",
    options: [
      "Je lis tout puis je cherche les données utiles",
      "Je cherche directement les nombres",
      "Je ne sais pas par où commencer",
      "Je demande quelle formule utiliser",
      "Je fais un schéma",
      "Je commence un calcul",
      "Je bloque",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Méthode de lecture d'énoncé et risque d'application mécanique",
    output_usage: ["teacher_brief", "method_recommendation", "first_lesson_plan"],
    interpretation_rules: {
      "Je cherche directement les nombres": "Risque d'application mécanique — besoin de sens",
      "Je demande quelle formule utiliser": "Besoin de sens et de stratégie",
      "Je fais un schéma": "Bon levier visuel à valoriser",
      "Je bloque": "Priorité méthode de lecture d'énoncé",
    },
  },

  {
    id: "math_03",
    section_key: "math_profile",
    domain: "mathematics",
    audience: "learner",
    profile: "teen",
    mode: "standard",
    question_text: "Les formules, pour toi, c'est surtout…",
    answer_type: "single_choice",
    options: [
      "Quelque chose à apprendre par cœur",
      "Une méthode que je comprends",
      "Quelque chose que j'utilise sans toujours comprendre",
      "Ce qui me bloque le plus",
      "Utile si j'ai un exemple",
      "Je ne sais pas",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Rapport procédural ou conceptuel aux formules mathématiques",
    output_usage: ["method_recommendation", "teacher_brief"],
  },

  {
    id: "math_04",
    section_key: "math_profile",
    domain: "mathematics",
    audience: "learner",
    profile: "all",
    mode: "standard",
    question_text: "Quand tu fais un calcul, ce qui arrive souvent est…",
    answer_type: "single_choice",
    options: [
      "Je fais des erreurs d'inattention",
      "Je ne sais pas quelle opération choisir",
      "Je comprends mais je vais lentement",
      "Je perds des étapes",
      "Je n'arrive pas à vérifier",
      "Je réussis surtout avec un modèle",
      "Autre",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Type d'erreur dominant dans le calcul",
    output_usage: ["error_watchlist", "teacher_brief"],
  },

  {
    id: "math_05",
    section_key: "math_profile",
    domain: "mathematics",
    audience: "learner",
    profile: "teen",
    mode: "standard",
    question_text: "Quand il faut rédiger une réponse, tu es plutôt…",
    answer_type: "single_choice",
    options: [
      "Je sais faire le calcul mais pas expliquer",
      "Je donne juste le résultat",
      "Je ne sais pas quoi écrire",
      "Je peux expliquer avec des mots simples",
      "Je rédige correctement si j'ai un modèle",
      "Je n'ai pas de difficulté particulière",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Capacité de rédaction mathématique et verbalisation",
    output_usage: ["teacher_brief", "error_watchlist"],
  },

  // ── PROFIL INFORMATIQUE ────────────────────

  {
    id: "cs_01",
    section_key: "cs_profile",
    domain: "computer_science",
    audience: "learner",
    profile: "all",
    mode: "standard",
    question_text: "Qu'est-ce qui te bloque le plus en informatique ou en programmation ?",
    answer_type: "multiple_choice",
    options: [
      "Comprendre la consigne",
      "Savoir par où commencer",
      "Comprendre les variables",
      "Comprendre les conditions",
      "Comprendre les boucles",
      "Comprendre les fonctions",
      "Écrire le code",
      "Corriger les erreurs",
      "Organiser les étapes",
      "Lire le code des autres",
      "Je ne sais pas",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Identifier les notions informatiques problématiques",
    output_usage: ["teacher_brief", "error_watchlist", "first_lesson_plan"],
  },

  {
    id: "cs_02",
    section_key: "cs_profile",
    domain: "computer_science",
    audience: "learner",
    profile: "all",
    mode: "standard",
    question_text: "Quand ton code ne marche pas, que fais-tu d'abord ?",
    answer_type: "single_choice",
    options: [
      "Je lis le message d'erreur",
      "Je relis mon code ligne par ligne",
      "Je change des choses au hasard",
      "Je demande directement la solution",
      "Je cherche sur internet",
      "J'ajoute des tests ou des print",
      "Je recommence tout",
      "Je bloque",
    ],
    required_status: "required",
    pedagogical_purpose: "Stratégie de debugging : méthodique, aléatoire, délégation, abandon",
    output_usage: ["teacher_brief", "method_recommendation", "error_watchlist"],
    interpretation_rules: {
      "Je lis le message d'erreur": "Bon début — à renforcer",
      "J'ajoute des tests ou des print": "Bonne autonomie de debugging",
      "Je change des choses au hasard": "Priorité méthode de debugging",
      "Je demande directement la solution": "Autonomie à travailler",
      "Je recommence tout": "Besoin d'isoler le problème",
    },
  },

  {
    id: "cs_03",
    section_key: "cs_profile",
    domain: "computer_science",
    audience: "learner",
    profile: "all",
    mode: "standard",
    question_text: "Quand tu dois écrire un programme, quelle étape est la plus difficile ?",
    answer_type: "single_choice",
    options: [
      "Comprendre le problème",
      "Découper en étapes",
      "Choisir les variables",
      "Écrire la syntaxe",
      "Utiliser les boucles et conditions",
      "Tester",
      "Corriger",
      "Expliquer ce que fait le code",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Phase critique dans le processus de conception de programme",
    output_usage: ["teacher_brief", "method_recommendation", "first_lesson_plan"],
  },

  {
    id: "cs_04",
    section_key: "cs_profile",
    domain: "computer_science",
    audience: "learner",
    profile: "teen",
    mode: "standard",
    question_text: "Quand tu lis du code, tu arrives à…",
    answer_type: "single_choice",
    options: [
      "Comprendre l'idée générale",
      "Suivre quelques lignes",
      "Comprendre avec des commentaires",
      "Comprendre seulement si quelqu'un explique",
      "Reconnaître certaines structures",
      "Je me perds rapidement",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Niveau de lecture de code, compréhension structurelle",
    output_usage: ["level_estimate", "teacher_brief"],
  },

  {
    id: "cs_05",
    section_key: "cs_profile",
    domain: "computer_science",
    audience: "learner",
    profile: "all",
    mode: "standard",
    question_text: "Pour apprendre le code, ce qui t'aide le plus est…",
    answer_type: "single_choice",
    options: [
      "Voir un exemple complet",
      "Modifier un exemple existant",
      "Construire un petit projet",
      "Résoudre des exercices courts",
      "Comprendre la logique avant la syntaxe",
      "Écrire beaucoup de code",
      "Corriger mes erreurs",
      "Travailler étape par étape",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Style d'apprentissage du code",
    output_usage: ["method_recommendation", "first_lesson_plan", "activity_personalization"],
  },

  // ── MINI-TÂCHES MATHS ──────────────────────

  {
    id: "mt_math_01",
    section_key: "math_mini_tasks",
    domain: "mathematics",
    audience: "learner",
    profile: "all",
    mode: "all",
    question_text: "Un cahier coûte 3 €. Léa achète 4 cahiers. Quelle opération permet de savoir combien elle paie ?",
    answer_type: "single_choice",
    options: ["3 + 4", "3 × 4", "4 - 3", "4 ÷ 3"],
    correct_answer: "3 × 4",
    required_status: "optional",
    pedagogical_purpose: "Compréhension d'un énoncé simple — sélection de l'opération pertinente",
    output_usage: ["level_estimate", "teacher_brief"],
  },

  {
    id: "mt_math_02",
    section_key: "math_mini_tasks",
    domain: "mathematics",
    audience: "learner",
    profile: "all",
    mode: "all",
    question_text: "On cherche le prix total de 5 objets identiques si un objet coûte 8 €. Quelle méthode est la plus adaptée ?",
    answer_type: "single_choice",
    options: ["Multiplier 8 par 5", "Additionner 8 et 5", "Soustraire 5 à 8", "Diviser 8 par 5"],
    correct_answer: "Multiplier 8 par 5",
    required_status: "optional",
    pedagogical_purpose: "Choix de méthode face à un énoncé multiplicatif simple",
    output_usage: ["level_estimate", "method_recommendation"],
  },

  {
    id: "mt_math_03",
    section_key: "math_mini_tasks",
    domain: "mathematics",
    audience: "learner",
    profile: "all",
    mode: "all",
    question_text: "Tu trouves 2 comme résultat à 9 × 7. Que devrais-tu faire ?",
    answer_type: "single_choice",
    options: [
      "Garder la réponse",
      "Vérifier car le résultat semble trop petit",
      "Changer au hasard",
      "Demander directement la solution",
    ],
    correct_answer: "Vérifier car le résultat semble trop petit",
    required_status: "optional",
    pedagogical_purpose: "Rapport à la vérification et au sens du résultat",
    output_usage: ["error_watchlist", "teacher_brief"],
  },

  {
    id: "mt_math_04",
    section_key: "math_mini_tasks",
    domain: "mathematics",
    audience: "learner",
    profile: "teen",
    mode: "standard",
    question_text: "Une formule sert surtout à…",
    answer_type: "single_choice",
    options: [
      "Mémoriser sans comprendre",
      "Organiser une relation entre des éléments",
      "Éviter de réfléchir",
      "Donner toujours la même réponse",
    ],
    correct_answer: "Organiser une relation entre des éléments",
    required_status: "optional",
    pedagogical_purpose: "Sens attribué aux formules — procédural vs conceptuel",
    output_usage: ["method_recommendation", "teacher_brief"],
  },

  {
    id: "mt_math_05",
    section_key: "math_mini_tasks",
    domain: "mathematics",
    audience: "learner",
    profile: "teen",
    mode: "standard",
    question_text: "Explique en une phrase comment tu fais pour calculer 25 % de 80.",
    answer_type: "short_text",
    max_words: 100,
    required_status: "optional",
    pedagogical_purpose: "Verbalisation d'une procédure mathématique — rédaction, méthode",
    output_usage: ["teacher_brief", "level_estimate"],
  },

  // ── MINI-TÂCHES INFORMATIQUE ───────────────

  {
    id: "mt_cs_01",
    section_key: "cs_mini_tasks",
    domain: "computer_science",
    audience: "learner",
    profile: "all",
    mode: "all",
    question_text: "Si une personne a 18 ans ou plus, elle est majeure. Quelle condition représente cela en code ?",
    answer_type: "single_choice",
    options: ["age > 18", "age >= 18", "age < 18", "age = 18 seulement"],
    correct_answer: "age >= 18",
    required_status: "optional",
    pedagogical_purpose: "Compréhension des conditions logiques (strict vs large)",
    output_usage: ["level_estimate", "teacher_brief"],
  },

  {
    id: "mt_cs_02",
    section_key: "cs_mini_tasks",
    domain: "computer_science",
    audience: "learner",
    profile: "all",
    mode: "all",
    question_text: "Une boucle sert surtout à…",
    answer_type: "single_choice",
    options: [
      "Répéter une action",
      "Choisir entre deux actions",
      "Stocker une valeur",
      "Afficher une erreur",
    ],
    correct_answer: "Répéter une action",
    required_status: "optional",
    pedagogical_purpose: "Compréhension du concept de boucle",
    output_usage: ["level_estimate", "teacher_brief"],
  },

  {
    id: "mt_cs_03",
    section_key: "cs_mini_tasks",
    domain: "computer_science",
    audience: "learner",
    profile: "all",
    mode: "all",
    question_text: "Voici un bout de code :\nx = 5\ny = 0\nresult = x / y\n\nQuel est le problème probable ?",
    answer_type: "single_choice",
    options: [
      "Division par zéro",
      "Variable x trop grande",
      "Manque de boucle",
      "Aucun problème",
    ],
    correct_answer: "Division par zéro",
    required_status: "optional",
    pedagogical_purpose: "Lecture de code et identification d'erreur logique simple",
    output_usage: ["level_estimate", "error_watchlist", "teacher_brief"],
  },

  {
    id: "mt_cs_04",
    section_key: "cs_mini_tasks",
    domain: "computer_science",
    audience: "learner",
    profile: "all",
    mode: "all",
    question_text: "Avant d'écrire du code, quelle étape aide le plus ?",
    answer_type: "single_choice",
    options: [
      "Découper le problème en petites étapes",
      "Écrire tout directement",
      "Copier une solution existante",
      "Changer de langage",
    ],
    correct_answer: "Découper le problème en petites étapes",
    required_status: "optional",
    pedagogical_purpose: "Méthode de décomposition — pensée algorithmique",
    output_usage: ["method_recommendation", "teacher_brief"],
  },

  {
    id: "mt_cs_05",
    section_key: "cs_mini_tasks",
    domain: "computer_science",
    audience: "learner",
    profile: "teen",
    mode: "standard",
    question_text: "Explique en une phrase ce que fait une variable dans un programme.",
    answer_type: "short_text",
    max_words: 100,
    required_status: "optional",
    pedagogical_purpose: "Verbalisation du concept de variable — compréhension profonde",
    output_usage: ["level_estimate", "teacher_brief"],
  },

  // ── CONTEXTE PARENT ────────────────────────

  {
    id: "par_01",
    section_key: "parent_context",
    domain: "all",
    audience: "parent",
    profile: "all",
    mode: "all",
    question_text: "Dans quelles situations l'élève rencontre-t-il le plus de difficultés ?",
    answer_type: "multiple_choice",
    options: [
      "Devoirs",
      "Contrôles",
      "Compréhension du cours",
      "Exercices nouveaux",
      "Problèmes avec texte",
      "Calculs",
      "Programmation",
      "Autonomie",
      "Gestion du stress",
      "Organisation",
    ],
    required_status: "required",
    pedagogical_purpose: "Contexte familial des difficultés scolaires",
    output_usage: ["parent_advice", "teacher_brief"],
  },

  {
    id: "par_02",
    section_key: "parent_context",
    domain: "all",
    audience: "parent",
    profile: "all",
    mode: "all",
    question_text: "Qu'observez-vous lorsqu'il/elle bloque ?",
    answer_type: "single_choice",
    options: [
      "Demande vite de l'aide",
      "Abandonne rapidement",
      "S'énerve ou panique",
      "Dit qu'il/elle est nul(le)",
      "Essaie longtemps sans méthode",
      "Attend la correction",
      "Réussit avec un exemple mais pas seul",
      "Difficile à observer",
    ],
    required_status: "required",
    pedagogical_purpose: "Comportement observé en situation de blocage",
    output_usage: ["teacher_brief", "confidence_support", "parent_advice"],
  },

  {
    id: "par_03",
    section_key: "parent_context",
    domain: "all",
    audience: "parent",
    profile: "all",
    mode: "all",
    question_text: "Qu'aimeriez-vous qu'il/elle puisse réussir dans les prochaines semaines ?",
    answer_type: "short_text",
    max_words: 180,
    required_status: "required",
    pedagogical_purpose: "Objectif parental concret pour orienter le plan",
    output_usage: ["parent_advice", "plan_4_weeks"],
  },

  {
    id: "par_04",
    section_key: "parent_context",
    domain: "all",
    audience: "parent",
    profile: "all",
    mode: "standard",
    question_text: "Qu'est-ce qui semble le/la motiver davantage ?",
    answer_type: "single_choice",
    options: [
      "Réussir les devoirs",
      "Avoir de meilleures notes",
      "Comprendre enfin",
      "Préparer un examen",
      "Faire un projet",
      "Utiliser l'informatique concrètement",
      "Reprendre confiance",
      "Devenir plus autonome",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Levier de motivation selon la perspective parent",
    output_usage: ["parent_advice", "activity_personalization"],
  },

  {
    id: "par_05",
    section_key: "parent_context",
    domain: "all",
    audience: "parent",
    profile: "all",
    mode: "standard",
    question_text: "Y a-t-il une information importante que le professeur devrait connaître ?",
    answer_type: "long_text",
    required_status: "optional",
    help_text: "Évitez les informations sensibles inutiles. Restez sur ce qui peut aider l'accompagnement pédagogique.",
    pedagogical_purpose: "Contexte personnel ou scolaire non couvert par les autres questions",
    output_usage: ["teacher_brief"],
  },

  // ── OBSERVATION PROFESSEUR ─────────────────

  {
    id: "obs_01",
    section_key: "teacher_observation",
    domain: "all",
    audience: "teacher",
    profile: "all",
    mode: "all",
    question_text: "Quel type de blocage semble dominant chez cet élève ?",
    answer_type: "single_choice",
    options: [
      "Compréhension d'énoncé",
      "Bases fragiles",
      "Méthode absente",
      "Application mécanique",
      "Manque de confiance",
      "Erreur de calcul",
      "Erreur de raisonnement",
      "Difficulté de rédaction",
      "Difficulté de debugging",
      "Difficulté d'abstraction",
      "Autonomie faible",
      "Autre",
    ],
    required_status: "required",
    pedagogical_purpose: "Diagnostic pédagogique principal du professeur",
    output_usage: ["teacher_brief", "method_recommendation"],
  },

  {
    id: "obs_02",
    section_key: "teacher_observation",
    domain: "all",
    audience: "teacher",
    profile: "all",
    mode: "all",
    question_text: "Comment l'élève réagit-il face à l'erreur ?",
    answer_type: "single_choice",
    options: [
      "Analyse l'erreur",
      "Accepte l'aide",
      "Recommence sans stratégie",
      "Abandonne vite",
      "Panique",
      "Masque ses difficultés",
      "Attend la solution",
      "Non observé",
    ],
    required_status: "required",
    pedagogical_purpose: "Comportement observé face à l'erreur — base de la stratégie de correction",
    output_usage: ["teacher_brief", "correction_strategy", "confidence_support"],
  },

  {
    id: "obs_03",
    section_key: "teacher_observation",
    domain: "all",
    audience: "teacher",
    profile: "all",
    mode: "all",
    question_text: "Comment l'élève raisonne-t-il/elle ?",
    answer_type: "single_choice",
    options: [
      "Cherche une méthode claire",
      "Applique sans comprendre",
      "Teste plusieurs pistes",
      "Attend la procédure",
      "Comprend mais ne structure pas",
      "Raisonnement prometteur mais fragile",
      "Difficile à observer",
    ],
    required_status: "required",
    pedagogical_purpose: "Profil de raisonnement — procédural, logique, exploratoire",
    output_usage: ["teacher_brief", "reasoning_profile", "method_recommendation"],
  },

  {
    id: "obs_04",
    section_key: "teacher_observation",
    domain: "all",
    audience: "teacher",
    profile: "all",
    mode: "standard",
    question_text: "Quel niveau de guidage semble nécessaire ?",
    answer_type: "single_choice",
    options: [
      "Très guidé",
      "Guidé avec exemples",
      "Semi-autonome",
      "Autonome avec vérification",
      "Autonome",
      "À confirmer",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Niveau d'autonomie observable, base du plan de progression",
    output_usage: ["teacher_brief", "first_lesson_plan", "plan_4_weeks"],
  },

  {
    id: "obs_05",
    section_key: "teacher_observation",
    domain: "all",
    audience: "teacher",
    profile: "all",
    mode: "standard",
    question_text: "Quelle posture pédagogique recommandez-vous pour cet élève ?",
    answer_type: "single_choice",
    options: [
      "Rassurer avant de complexifier",
      "Reconstruire les bases",
      "Travailler la méthode",
      "Verbaliser le raisonnement",
      "Faire pratiquer progressivement",
      "Corriger les erreurs récurrentes",
      "Travailler par projets",
      "Travailler par problèmes courts",
    ],
    required_status: "recommended",
    pedagogical_purpose: "Posture pédagogique recommandée par le professeur",
    output_usage: ["teacher_brief", "method_recommendation"],
  },

  {
    id: "obs_06",
    section_key: "teacher_observation",
    domain: "all",
    audience: "teacher",
    profile: "all",
    mode: "standard",
    question_text: "Quelle première séance semble la plus pertinente pour cet élève ?",
    answer_type: "short_text",
    max_words: 200,
    required_status: "optional",
    pedagogical_purpose: "Recommandation concrète de première séance par le professeur",
    output_usage: ["first_lesson_plan", "teacher_brief"],
  },

  {
    id: "obs_07",
    section_key: "teacher_observation",
    domain: "all",
    audience: "teacher",
    profile: "all",
    mode: "standard",
    question_text: "Quelles erreurs ou comportements faut-il surveiller chez cet élève ?",
    answer_type: "multiple_choice",
    options: [
      "Erreurs de calcul",
      "Confusion de formules",
      "Lecture trop rapide",
      "Absence de méthode",
      "Rédaction incomplète",
      "Panique face à l'erreur",
      "Syntaxe (code)",
      "Variables mal comprises",
      "Boucles mal utilisées",
      "Conditions mal comprises",
      "Debugging au hasard",
      "Autre",
    ],
    required_status: "optional",
    pedagogical_purpose: "Watchlist d'erreurs et comportements à surveiller",
    output_usage: ["error_watchlist", "teacher_brief"],
  },
];

// ─────────────────────────────────────────────
// HELPER FUNCTIONS
// ─────────────────────────────────────────────

/** Get questions for a session, filtered by domain, profile, respondent, mode, sections */
export function getQuestionsForSession({ domain = "mathematics", profile = "adult", respondentType = "learner", mode = "standard", sections = [] }) {
  return QUESTIONS.filter(q => {
    // Section filter
    if (sections.length && !sections.includes(q.section_key)) return false;
    // Audience
    if (q.audience !== respondentType) return false;
    // Profile
    if (q.profile !== "all" && q.profile !== profile) return false;
    // Mode
    if (q.mode !== "all" && q.mode !== mode) return false;
    // Domain
    if (q.domain !== "all") {
      if (domain === "mixed") {
        if (!["mathematics", "computer_science", "mixed", "all"].includes(q.domain)) return false;
      } else {
        if (q.domain !== domain) return false;
      }
    }
    return true;
  });
}

export const RESPONDENT_LABELS = {
  learner: "Élève",
  parent: "Parent",
  teacher: "Professeur",
};

export const DOMAIN_LABELS = {
  mathematics: "Mathématiques",
  computer_science: "Informatique",
  mixed: "Maths & Informatique",
};